from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from reportlab.lib import colors
from fastapi.templating import Jinja2Templates
from datetime import datetime
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
) 
from reportlab.lib.styles import getSampleStyleSheet

from agents.coordinator_agent import CoordinatorAgent
from api.schemas import InvestigationRequest, InvestigationResponse


app = FastAPI(
    title="Banking Fraud Investigation API",
    description="Agentic AI Banking Fraud Investigation System",
    version="1.0.0"
)


# Static files (CSS, JS)
app.mount(
    "/static",
    StaticFiles(directory="frontend/static"),
    name="static"
)


# HTML templates
templates = Jinja2Templates(
    directory="frontend/templates"
)


# Initialize Coordinator Agent
coordinator = CoordinatorAgent()
latest_report = None


@app.get("/", response_class=HTMLResponse)
def home(request: Request):
    """
    Display the Banking Fraud Investigation webpage.
    """

    return templates.TemplateResponse(
        request=request,
        name="index.html",
        context={}
    )


@app.post(
    "/investigate",
    response_model=InvestigationResponse
)
def investigate_transaction(request: InvestigationRequest):
    """
    Investigate a banking transaction.
    """

    global latest_report

    report = coordinator.run(request.transaction_id)

    latest_report = report


    # Handle failed investigation
    if report.get("decision") == "Failed":
        raise HTTPException(
            status_code=404,
            detail=report["reason"]
        )


       # Return complete investigation report
    return InvestigationResponse(
        decision=report["decision"],
        status=report["status"],

        transaction_id=report["transaction_id"],
        customer_id=report["customer_id"],

        transaction_details=report["transaction_details"],

        customer_details=report["customer_details"],

        fraud_analysis=report["fraud_analysis"],

        decision_analysis=report["decision_analysis"],

        investigation_summary=report["investigation_summary"]
    
    )

@app.get("/download-pdf")
def download_pdf():

    global latest_report

    if latest_report is None:
        raise HTTPException(
            status_code=404,
            detail="No investigation report available"
        )


    file_name = "Banking_Fraud_Investigation_Report.pdf"


    pdf = SimpleDocTemplate(
        file_name,
        pagesize=letter
    )


    styles = getSampleStyleSheet()

    content = []

    title_style = ParagraphStyle(
      "TitleStyle",
      parent=styles["Heading1"],
      alignment=TA_CENTER,
      fontSize=22,
      textColor=HexColor("#0B3C5D"),
      spaceAfter=20,
)

    heading_style = ParagraphStyle(
     "HeadingStyle",
       parent=styles["Heading2"],
       alignment=TA_LEFT,
       fontSize=15,
       textColor=HexColor("#0B3C5D"),
       spaceBefore=16,
       spaceAfter=8,
)

    normal_style = ParagraphStyle(
      "NormalStyle",
       parent=styles["BodyText"],
      fontSize=10,
      leading=18,
      spaceAfter=6,
)

    footer_style = ParagraphStyle(
      "FooterStyle",
       parent=styles["BodyText"],
       alignment=TA_CENTER,
       fontSize=8,
       textColor=HexColor("#666666"),
)


   
    # Title

    content.append(
      Paragraph(
        "BANKING FRAUD INVESTIGATION REPORT",
        title_style
    )
)

    content.append(
      Paragraph(
        "Prepared by the Agentic AI Banking Fraud Investigation System",
        normal_style
    )
)

    content.append(Spacer(1, 20))
    

    content.append(
    Paragraph(
        f"<b>Report Generated:</b> {datetime.now().strftime('%d %B %Y  %I:%M %p')}",
        normal_style
    )
)

    content.append(
    Paragraph(
        "<b>Generated By:</b> Agentic AI Banking Fraud Investigation System",
        normal_style
    )
)

    content.append(
    Paragraph(
        "<b>Report Version:</b> 1.0",
        normal_style
    )
)

    content.append(Spacer(1, 20))


  # EXECUTIVE SUMMARY

    content.append(
    Paragraph(
        "EXECUTIVE SUMMARY",
        heading_style
    )
)
    decision = latest_report["decision_analysis"]

    executive_summary = f"""
    This report presents the findings of an automated fraud investigation
    conducted by the Agentic AI Banking Fraud Investigation System for
    Transaction ID <b>{latest_report['transaction_id']}</b>.

    The investigation analyzed transaction details, customer information,
    and multiple fraud indicators using specialized AI agents.

    Based on the overall analysis, the transaction received a fraud score of
    <b>{decision['fraud_score']}</b>, which corresponds to a
    <b>{decision['risk_level']}</b> risk level.

    The system recommends:
    <b>{decision['recommendation']}</b>.
"""
    content.append(
    Paragraph(
        executive_summary,
        normal_style
    )
)

    content.append(Spacer(1,20))


    
    # Investigation Summary
    

    Paragraph(
    "INVESTIGATION SUMMARY",
    heading_style
)

    content.append(
    Paragraph(
        "The following section provides an overview of the investigated transaction and summarizes the key findings produced by the Agentic AI Banking Fraud Investigation System.",
        normal_style
    )
)

    content.append(Spacer(1,10))


    decision = latest_report["decision_analysis"]


    summary_data = [

    ["Field", "Value", "Analysis"],

    [
        "Transaction ID",
        str(latest_report["transaction_id"]),
        "Unique identifier assigned to the investigated transaction."
    ],

    [
        "Customer ID",
        str(latest_report["customer_id"]),
        "Unique identifier of the customer involved in the transaction."
    ],

    [
        "Fraud Score",
        str(decision["fraud_score"]),
        "Overall fraud score calculated by the Decision Agent using multiple fraud indicators."
    ],

    [
        "Risk Level",
        decision["risk_level"],
        "Risk classification determined from the calculated fraud score."
    ],

    [
        "Recommendation",
        decision["recommendation"],
        "Recommended action generated after evaluating all investigation findings."
    ]

]

    table = Table(
    summary_data,
    colWidths=[120, 100, 260]
)

    table.setStyle(
    TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0B3C5D")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0,0), (-1,0), 10),

        ("BACKGROUND", (0,1), (-1,-1), colors.beige),

        ("VALIGN", (0,0), (-1,-1), "TOP"),

        ("BOTTOMPADDING", (0,1), (-1,-1), 8)

    ])
)

    content.append(table)

    content.append(Spacer(1,20))


    
    # Transaction Agent
   

    content.append(
        Paragraph(
            "TRANSACTION AGENT REPORT",
            heading_style
        )
    )

    content.append(
    Paragraph(
        "The Transaction Agent analyzed the financial transaction by examining its amount, date, time, type and geographical location. These attributes help determine whether the transaction follows expected banking behaviour or exhibits suspicious characteristics.",
        normal_style
    )
)

    content.append(Spacer(1,10))


    transaction = latest_report["transaction_details"]


    transaction_data = [

    ["Field", "Value", "Analysis"],

    [
        "Transaction Amount",
        str(transaction["transaction_amount"]),
        "Amount involved in the investigated transaction. Large transaction amounts generally require additional verification."
    ],

    [
        "Transaction Date",
        str(transaction["transaction_date"]),
        "Date on which the transaction was performed."
    ],

    [
        "Transaction Time",
        str(transaction["transaction_time"]),
        "Time of transaction execution. Transactions at unusual hours may increase fraud risk."
    ],

    [
        "Transaction Type",
        str(transaction["transaction_type"]),
        "Type of financial activity performed by the customer."
    ],

    [
        "Transaction Location",
        str(transaction["transaction_location"]),
        "Location where the transaction originated. This is compared with the customer's usual location during fraud analysis."
    ]

]

    table = Table(
    transaction_data,
    colWidths=[120, 100, 260]
)

    table.setStyle(
    TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0B3C5D")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0,0), (-1,0), 10),

        ("BACKGROUND", (0,1), (-1,-1), colors.beige),

        ("VALIGN", (0,0), (-1,-1), "TOP"),

        ("BOTTOMPADDING", (0,1), (-1,-1), 8)

    ])
) 

    content.append(table)

    content.append(Spacer(1,20))


    # Customer Agent
    

    content.append(
        Paragraph(
            "CUSTOMER AGENT REPORT",
            heading_style
        )
    )

    content.append(
    Paragraph(
        "The Customer Agent evaluated the customer's profile, account information and historical behaviour. Previous fraud history and transaction patterns were reviewed to assess the customer's overall fraud risk.",
        normal_style
    )
)

    content.append(Spacer(1,10))


    customer = latest_report["customer_details"]


    customer_data = [

    ["Field", "Value", "Analysis"],

    [
        "Home Location",
        str(customer["home_location"]),
        "Customer's registered home location used to compare transaction origin and identify suspicious activity."
    ],

    [
        "Card Type",
        str(customer["card_type"]),
        "Payment card used to perform the transaction."
    ],

    [
        "Account Balance",
        str(customer["account_balance"]),
        "Available account balance at the time of investigation."
    ],

    [
        "Previous Fraud Count",
        str(customer["previous_fraud_count"]),
        "Number of previously confirmed fraudulent activities associated with the customer."
    ],

    [
        "Total Transactions",
        str(customer["total_transactions"]),
        "Total number of historical transactions analyzed for customer behavior."
    ]

]


    table = Table(
    customer_data,
    colWidths=[120, 100, 260]
)

    table.setStyle(
    TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0B3C5D")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0,0), (-1,0), 10),

        ("BACKGROUND", (0,1), (-1,-1), colors.beige),

        ("VALIGN", (0,0), (-1,-1), "TOP"),

        ("BOTTOMPADDING", (0,1), (-1,-1), 8)

    ])
)


    content.append(table)

    content.append(Spacer(1,20))


    
    # Fraud Agent
   

    content.append(
        Paragraph(
            "FRAUD AGENT REPORT",
            heading_style
        )
    )

    content.append(
    Paragraph(
        "The Fraud Agent evaluated several fraud indicators commonly associated with suspicious banking activity. Each indicator contributes to the overall fraud assessment and assists in determining the final risk level.",
        normal_style
    )
)

    content.append(Spacer(1,10))


    fraud = latest_report["fraud_analysis"]


    fraud_data = [

    ["Fraud Indicator", "Value", "Analysis"],

    [
        "International Transaction",
        str(fraud["is_international_transaction"]),
        "International transactions generally require additional verification because they may indicate unauthorized account usage."
    ],

    [
        "New Merchant",
        str(fraud["is_new_merchant"]),
        "Transactions with merchants that have not been used previously may increase fraud risk."
    ],

    [
        "Unusual Time",
        str(fraud["unusual_time_transaction"]),
        "Transactions performed outside the customer's normal activity hours may indicate suspicious behavior."
    ],

    [
        "Failed Transaction Count",
        str(fraud["failed_transaction_count"]),
        "Multiple failed transaction attempts before a successful payment can indicate fraudulent activity."
    ],

    [
        "Distance From Home",
        str(fraud["distance_from_home"]),
        "Large distances between the customer's registered location and transaction location may indicate location anomalies."
    ]

]


    table = Table(
    fraud_data,
    colWidths=[120, 100, 260]
)
    table.setStyle(
    TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0B3C5D")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0,0), (-1,0), 10),

        ("BACKGROUND", (0,1), (-1,-1), colors.beige),

        ("VALIGN", (0,0), (-1,-1), "TOP"),

        ("BOTTOMPADDING", (0,1), (-1,-1), 8)

    ])
)


    content.append(table)

    content.append(Spacer(1,20))

   
# DECISION AGENT REPORT


    content.append(
      Paragraph(
        "DECISION AGENT REPORT",
        heading_style
    )
)
    
    content.append(
    Paragraph(
        "The Decision Agent reviewed the findings produced by all previous agents and generated the final fraud score, risk classification and recommended course of action.",
        normal_style
    )
)

    content.append(Spacer(1,10))
    

    decision_data = [

    ["Decision Factor", "Value", "Analysis"],

    [
        "Fraud Score",
        str(decision["fraud_score"]),
        "The fraud score represents the cumulative risk calculated from all detected fraud indicators."
    ],

    [
        "Risk Level",
        decision["risk_level"],
        "The overall risk classification assigned after evaluating all transaction, customer, and fraud indicators."
    ],

    [
        "Recommendation",
        decision["recommendation"],
        "The final action recommended by the Decision Agent based on the complete investigation."
    ]

]
    
    table = Table(
    decision_data,
    colWidths=[120,100,260]
)
    
    table.setStyle(
    TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0B3C5D")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0,0), (-1,0), 10),

        ("BACKGROUND", (0,1), (-1,-1), colors.beige),

        ("VALIGN", (0,0), (-1,-1), "TOP"),

        ("BOTTOMPADDING", (0,1), (-1,-1), 8)

    ])
)

    content.append(table)

    content.append(Spacer(1,20))


    
    # AI Summary
   

    summary = latest_report["investigation_summary"]

# Preserve line breaks
    summary = summary.replace("\n", "<br/><br/>")

# Highlight common headings if present
    summary = summary.replace(
      "**Executive Summary**",
      "<b>Executive Summary</b>"
)

    summary = summary.replace(
      "**Decision Justification**",
      "<br/><br/><b>Decision Justification</b>"
)

    summary = summary.replace(
    "**Final Recommendation**",
    "<br/><br/><b>Final Recommendation</b>"
)

    content.append(
      Paragraph(
        summary,
        normal_style
    )
)


    
# CONCLUSION


    content.append(
    Paragraph(
        "CONCLUSION",
        heading_style
    )
)

    conclusion = f"""
    The investigation was completed successfully using the Agentic AI Banking
    Fraud Investigation System. After evaluating transaction characteristics,
    customer behavior, historical fraud records, and fraud indicators,
    the transaction was classified as
    <b>{decision['risk_level']}</b> risk with a fraud score of
    <b>{decision['fraud_score']}</b>.

    Based on the comprehensive analysis, the system recommends:
    <b>{decision['recommendation']}</b>.
"""

    content.append(
    Paragraph(
        conclusion,
        normal_style
    )
)

    content.append(Spacer(1,20))


    pdf.build(content)


    return FileResponse(
        file_name,
        media_type="application/pdf",
        filename=file_name
    )

